#ifndef _mqtt_const_H
#define _mqtt_const_H



#define MQTT_BROKER "192.168.1.228"
#define MQTT_PORT 1883

#define MQTT_USERNAME "admin"
#define MQTT_PASSWORD "public"

#define MQTT_TOPIC_PREFIX "CP_IOT/"
#define MQTT_TOPIC_PING "PING"
#define MQTT_TOPIC_PONG "PONG"
#define MQTT_TOPIC_TEMPERATURE "TEMPERATURE"
#define MQTT_TOPIC_LED "LED"
#define MQTT_TOPIC_MESSAGE_BOARD "MESSAGE_BOARD"

#define MQTT_TOPIC_PAGER_MESSAGE "PAGER_MESSAGE"
#define MQTT_TOPIC_RADIO_PLAY "RADIO/PLAY"
#define MQTT_TOPIC_RADIO_STOP "RADIO/STOP"



#endif //_mqtt_const_H
